# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
      GBlogBundle\Entity\User:
        algorithm: md5
        encode_as_base64: false
        iterations: 1

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_user:
            entity:
                class: GBlogBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            provider: db_user
            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: /admin/login
                check_path: /admin/login
                default_target_path: /admin
            logout:
                path: /admin/logout
                target: /admin

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

    access_control:
        - { path:  ^/admin/login, roles : IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin , roles : [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER] }
